#!/usr/bin/env perl
use Mojolicious::Lite;

use lib 'lib';
use AuthHelper::Schema;
use Mojolicious::Plugin::Bcrypt;

my ( $name, $pass ) = @ARGV;

plugin 'bcrypt';

my $password = app->bcrypt($pass);

my $schema = AuthHelper::Schema->connect('auth');

$schema->resultset('Account')->create({ name => $name, password => $password });
